(function(){
  'use strict';
  const C=window.AIPanel,$=s=>document.querySelector(s),clone=x=>JSON.parse(JSON.stringify(x));
  let state=C.fresh(),base=null,blocked=false,dirty=false,editingId=null,editingBaseline='',historyId=null,toastTimer;
  const current=()=>state.projects.find(p=>p.id===state.activeId);
  function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4200);}
  function alertStorage(message,conflict=false){const box=$('#storage-alert');box.replaceChildren();box.append(document.createTextNode(message));const download=document.createElement('button');download.textContent='この画面の入力をバックアップ';download.onclick=()=>exportState();box.append(download);if(conflict){const reload=document.createElement('button');reload.textContent='別タブの保存内容を読み込む';reload.onclick=()=>{if(confirm('この画面の未保存入力は破棄されます。必要なら先にバックアップしてください。読み込みますか？'))location.reload();};box.append(reload);}box.hidden=false;}
  function markDirty(){dirty=true;$('#save-state').textContent='未保存';}
  function save(){
    if(blocked){markDirty();return false;}
    try{
      const live=localStorage.getItem(C.KEY);
      if(live!==base){blocked=true;markDirty();alertStorage('別タブで変更されました。この画面の入力は自動で上書きしません。バックアップ後、保存内容を読み込み直してください。',true);return false;}
      const checked=C.validate(state),next=JSON.stringify(checked);localStorage.setItem(C.KEY,next);base=next;dirty=false;$('#save-state').textContent='保存済み · このブラウザ';$('#storage-alert').hidden=true;return true;
    }catch(e){markDirty();alertStorage('保存できませんでした。入力はこの画面に残っています。ブラウザを閉じず、バックアップしてください。');return false;}
  }
  function load(){try{base=localStorage.getItem(C.KEY);if(base!==null)state=C.validate(JSON.parse(base));}catch(e){blocked=true;alertStorage('保存データを読み込めません。元のデータを保護し、自動保存を停止しました。バックアップ画面から復元できます。');$('#save-state').textContent='自動保存停止';}}
  function transaction(fn){if(blocked){toast('保存が停止中です。上部の案内を確認してください。');return false;}const before=clone(state);fn();if(!save()){state=before;return false;}return true;}
  function renderProjects(){const list=$('#project-list');list.replaceChildren();state.projects.forEach(p=>{const b=document.createElement('button');b.className='project-item';b.dataset.project=p.id;b.setAttribute('aria-pressed',String(p.id===state.activeId));const span=document.createElement('span');span.textContent=p.name;b.append(span);b.onclick=()=>{if(p.id===state.activeId)return;if(transaction(()=>state.activeId=p.id))render();};list.append(b);});}
  function preview(){const p=current();$('#prompt-preview').value=C.build(p);$('#material-count').textContent=`${p.draft.material.length.toLocaleString()} / 30,000`;$('#refine-buttons').querySelectorAll('button').forEach(b=>b.disabled=!p.draft.answer.trim());$('#answer-copy').disabled=!p.draft.answer.trim();$('#request-copy').disabled=![p.draft.material,p.brief,p.decisions,p.handoff].some(v=>v.trim());$('#history-save').disabled=!(p.draft.material.trim()||p.draft.answer.trim());}
  function renderHistory(){const p=current();$('#history-count').textContent=p.history.length;const list=$('#history-list');list.replaceChildren();if(!p.history.length){const empty=document.createElement('p');empty.className='empty-history';empty.textContent='残しておきたい作業を「履歴に保存」で、ここに。';list.append(empty);}p.history.slice().reverse().forEach(h=>{const b=document.createElement('button');b.className='history-row';b.dataset.history=h.id;b.append(document.createTextNode((h.material.trim()||C.TASKS.find(t=>t.id===h.task).name).slice(0,45)));const date=document.createElement('small');date.textContent=new Date(h.at).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});b.append(date);b.onclick=()=>openHistory(h.id);list.append(b);});}
  function render(){const p=current();renderProjects();$('#project-title').textContent=p.name;$('#context-summary').textContent=(p.brief||p.handoff||'前提や好みを保存すると、依頼文に自動で含まれます。').slice(0,180);$('#context-preview').textContent=C.context(p);$('#material').value=p.draft.material;$('#extra').value=p.draft.extra;$('#answer').value=p.draft.answer;$('#task-buttons').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.task===p.draft.task)));$('#prompt-details').open=false;preview();renderHistory();}
  function download(text,name){const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function exportState(){const snapshot=clone(state);if($('#project-dialog').open){let p=editingId?snapshot.projects.find(x=>x.id===editingId):null;if(!p){p=C.project('未保存の案件');snapshot.projects.push(p);}for(const field of ['name','brief','rules','decisions','handoff'])p[field]=$(`#project-${field}`).value.trim();if(!p.name)p.name='未保存の案件';}download(JSON.stringify(snapshot,null,2),`ai-panel-${new Date().toISOString().slice(0,10)}.json`);}
  async function copy(text,message){try{if(!navigator.clipboard?.writeText)throw Error();await navigator.clipboard.writeText(text);toast(message);return true;}catch(e){const area=$('#manual-copy');area.value=text;$('#copy-dialog').showModal();area.focus();area.select();return false;}}
  function openProject(isNew=false,focusHandoff=false){editingId=isNew?null:current().id;const p=isNew?C.project(''):current();editingBaseline=JSON.stringify(p);$('#project-dialog-title').textContent=isNew?'新しい案件':'案件の前提・引き継ぎ';for(const field of ['name','brief','rules','decisions','handoff'])$(`#project-${field}`).value=p[field];$('#project-delete').hidden=isNew;$('#project-dialog').showModal();if(focusHandoff)$('#project-handoff').focus();else $('#project-name').focus();}
  function openHistory(id){const h=current().history.find(x=>x.id===id);if(!h)return;historyId=id;$('#history-title').textContent=C.TASKS.find(t=>t.id===h.task).name;$('#history-material').textContent=h.material||'（素材なし）';$('#history-prompt').textContent=h.prompt;$('#history-answer').textContent=h.answer||'（回答なし）';$('#history-dialog').showModal();}
  C.TASKS.forEach(t=>{const b=document.createElement('button');b.className='task-button';b.dataset.task=t.id;const title=document.createElement('strong');title.textContent=`${t.icon} ${t.name}`;const small=document.createElement('small');small.textContent=t.hint;b.append(title,small);b.onclick=()=>{current().draft.task=t.id;markDirty();save();$('#task-buttons').querySelectorAll('button').forEach(btn=>btn.setAttribute('aria-pressed',String(btn===b)));preview();};$('#task-buttons').append(b);});
  C.REFINES.forEach(r=>{const b=document.createElement('button');b.textContent=r.name;b.dataset.refine=r.id;b.onclick=async()=>{const text=C.refine(current(),r.id);$('#prompt-preview').value=text;$('#prompt-details').open=true;await copy(text,`「${r.name}」の修正依頼をコピーしました`);};$('#refine-buttons').append(b);});
  for(const field of ['material','extra','answer'])$(`#${field}`).addEventListener('input',()=>{current().draft[field]=$(`#${field}`).value;markDirty();save();preview();});
  $('#request-copy').onclick=async()=>{const p=current(),text=C.build(p);p.draft.sentPrompt=text;p.draft.sentSource=C.source(p);markDirty();save();$('#prompt-preview').value=text;await copy(text,'依頼文をコピーしました。普段のAIに貼り付けてください。');};
  $('#answer-copy').onclick=()=>copy(current().draft.answer,'回答をコピーしました');
  $('#project-add').onclick=()=>{if(state.projects.length>=100)return toast('案件は100件までです。');openProject(true);};$('#project-edit').onclick=()=>openProject();$('#handoff-edit').onclick=()=>openProject(false,true);
  $('#project-form').onsubmit=e=>{e.preventDefault();if(blocked)return toast('保存が停止中です。上部の案内を確認してください。');const name=$('#project-name').value.trim();if(!name)return $('#project-name').focus();if(editingId&&JSON.stringify(state.projects.find(p=>p.id===editingId))!==editingBaseline)return toast('この案件が更新されました。入力を控えてから開き直してください。');if(transaction(()=>{let p=editingId?state.projects.find(x=>x.id===editingId):C.project(name);for(const field of ['name','brief','rules','decisions','handoff'])p[field]=$(`#project-${field}`).value.trim();if(!editingId){state.projects.push(p);state.activeId=p.id;}})){$('#project-dialog').close();render();toast('案件ノートを保存しました');}};
  $('#project-delete').onclick=()=>{if(!confirm('この案件の前提・入力中の作業・履歴を削除します。よろしいですか？'))return;if(transaction(()=>{state.projects=state.projects.filter(p=>p.id!==editingId);if(!state.projects.length)state.projects.push(C.project());if(!state.projects.some(p=>p.id===state.activeId))state.activeId=state.projects[0].id;})){$('#project-dialog').close();render();toast('案件を削除しました');}};
  $('#history-save').onclick=()=>{const p=current(),last=p.history.at(-1);if(last&&['task','material','extra','answer','sentPrompt','sentSource'].every(k=>last[k]===p.draft[k]))return toast('同じ内容はすでに履歴に保存されています');if(p.history.length>=30&&!confirm('履歴は30件までです。最も古い1件を削除して保存しますか？'))return;if(transaction(()=>{p.history.push({id:C.uid(),at:Date.now(),...clone(p.draft),prompt:p.draft.sentPrompt||C.build(p)});if(p.history.length>30)p.history.shift();})){renderHistory();toast('この作業を履歴に保存しました');}};
  $('#new-work').onclick=()=>{const p=current();if((p.draft.material||p.draft.answer||p.draft.extra)&&!confirm('入力中の素材・回答を空にします。必要なら先に履歴へ保存してください。新しい作業を始めますか？'))return;if(transaction(()=>p.draft=C.draft())){render();$('#material').focus();}};
  $('#history-restore').onclick=()=>{const h=current().history.find(x=>x.id===historyId);if(!h)return;if(!confirm('入力中の作業を、この履歴の内容に置き換えますか？'))return;if(transaction(()=>{current().draft=Object.fromEntries(Object.keys(C.draft()).map(k=>[k,h[k]]));})){$('#history-dialog').close();render();toast('保存した作業を再開しました。案件の前提は現在の内容です。');}};
  $('#history-delete').onclick=()=>{if(!confirm('この履歴を削除しますか？'))return;if(transaction(()=>current().history=current().history.filter(h=>h.id!==historyId))){$('#history-dialog').close();renderHistory();}};
  $('#backup-open').onclick=()=>{$('#import-status').textContent='';$('#backup-dialog').showModal();};$('#export').onclick=exportState;
  $('#import').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;let imported;try{if(file.size>10000000)throw Error('10MB以下のファイルを選択してください。');imported=C.validate(JSON.parse(await file.text()));}catch(err){$('#import-status').textContent='復元できません：'+err.message;return;}
    if(!confirm(`${imported.projects.length}件の案件で、AI作業パネルの全データを置き換えますか？`))return;
    try{const live=localStorage.getItem(C.KEY);if(live!==base){blocked=true;alertStorage('別タブで変更されました。保存内容を読み込み直してから復元してください。',true);return;}const next=JSON.stringify(imported);localStorage.setItem(C.KEY,next);state=imported;base=next;blocked=false;dirty=false;$('#storage-alert').hidden=true;$('#save-state').textContent='保存済み · このブラウザ';$('#backup-dialog').close();render();toast('バックアップを復元しました');}catch(err){$('#import-status').textContent='保存できませんでした。既存データは変更していません。';}
  };
  function projectFormDirty(){if(!$('#project-dialog').open)return false;const original=JSON.parse(editingBaseline);return ['name','brief','rules','decisions','handoff'].some(k=>$(`#project-${k}`).value!==original[k]);}
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(b.dataset.close==='project-dialog'&&projectFormDirty()&&!confirm('未保存の案件ノートを破棄しますか？'))return;$(`#${b.dataset.close}`).close();});
  $('#project-dialog').addEventListener('cancel',e=>{if(projectFormDirty()&&!confirm('未保存の案件ノートを破棄しますか？'))e.preventDefault();});
  window.addEventListener('beforeunload',e=>{if(dirty||projectFormDirty()){e.preventDefault();e.returnValue='';}});
  window.addEventListener('storage',e=>{if(e.key!==C.KEY&&e.key!==null)return;const live=localStorage.getItem(C.KEY);if(live===base)return;blocked=true;markDirty();alertStorage('別タブで変更されました。この画面の入力を保護するため、自動保存を停止しました。',true);});
  load();render();
})();
